name: "test on V2"

on:
  push:
    paths:
# this ensures that tests are run when adding new tests, but docker image is only published with the other pipeline when source code is changed
      - 'tests/**'
      - 'build/**'
  pull_request:
    branches: [ main ]
    paths:
# here, also run tests when a pr targets source files
      - 'tests/**'
      - 'src/**'
      - 'build/**'

jobs:
  build-and-test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: make script executable
      run: chmod u+x build.sh
    - name: Build and test
      working-directory: ./
      run: ./build.sh runtests

  build-and-test-windows:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: Build and test
      working-directory: ./
      run: ./build.cmd runtests